<?php
/** @var \TIG\TinyCDN\Block\Adminhtml\Config\Support\SupportTab $this */
?>
<div id="supporttab" class="tig-tinycdn-supporttab" data-mage-init='{"tinyConfig": true}'>

    <div class="colset-2">

        <div id="legend">
            <h3 ><?php echo $block->escapeHtml(__('Legend'));?></h3>
            <ul>
                <li class="disabled">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Disabled'));?></span>
                </li>
                <li class="test">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Test Mode'));?></span>
                </li>
                <li class="live">
                    <span class="img"></span>
                    <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                    <span class="status"><?php echo $block->escapeHtml(__('Live Mode'));?></span>
                </li>
            </ul>
        </div>

        <div class="col-1 version-compatibility">
            <h3 ><?php echo $block->escapeHtml(__('Magento version compatibility'));?></h3>
            <ul>
                <li>
                    <span class="text">
                        <?php echo $block->escapeHtml(__('Supported Magento versions'));?>:
                    </span>
                    <span class="version"><?php echo $block->escapeHtml($this->getSupportedMagentoVersions()); ?></span>
                </li>
                <li>
                    <span class="text"><?php echo $block->escapeHtml(__('TinyCDN version'));?>:</span>
                    <span class="version"><?php echo $block->escapeHtml($this->getVersionNumber()); ?></span>
                </li>
            </ul>
        </div>

        <div class="col-2 version-compatibility">
            <img class="panda-george" src="<?php echo $this->getViewFileUrl('TIG_TinyCDN::images/george-magento@2x_opt.png'); ?>" alt="George the TinyCDN panda" />
        </div>

    </div>

    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Support'));?></h3>
        </div>
        <div class="collapse-content support-tinycdn-tig" data-role="content" style="display:none;">
            <?php echo __('This extension is developed by <a href="https://tig.nl" target="_BLANK">TIG</a>');?>

            <div class="colset-2">
                <div class="col-1">
                    <h4><?php echo __('Extension basic configuration and account information');?></h4>
                    <?php echo __('Please contact:'); ?> <a href="mailto:support@tinypng.com">support@tinypng.com</a>
                </div>
                <div class="col-2">

                </div>

            </div>
        </div>
    </div>
</div>
