<?php
/** @var \TIG\TinyCDN\Block\Adminhtml\Config\Support\SupportTab $this */
?>
<div id="supporttab" class="tig-tinycdn-supporttab" data-mage-init='{"tinyConfig": true}'>

    <div class="colset-2">

        <div class="col-1 legend-version">
            <div id="legend">
                <h3 ><?php echo $block->escapeHtml(__('Legend'));?></h3>
                <ul>
                    <li class="disabled">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Disabled'));?></span>
                    </li>
                    <li class="test">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Test Mode'));?></span>
                    </li>
                    <li class="live">
                        <span class="img"></span>
                        <span class="text"><?php echo $block->escapeHtml(__('Extension status'));?>: </span>
                        <span class="status"><?php echo $block->escapeHtml(__('Live Mode'));?></span>
                    </li>
                </ul>
            </div>

            <div class="version-compatibility">
                <h3 ><?php echo $block->escapeHtml(__('Magento version compatibility'));?></h3>
                <ul>
                    <li>
                    <span class="text">
                        <?php echo $block->escapeHtml(__('Supported Magento versions'));?>:
                    </span>
                        <span class="version"><?php echo $block->escapeHtml($this->getSupportedMagentoVersions()); ?></span>
                    </li>
                    <li>
                        <span class="text"><?php echo $block->escapeHtml(__('TinyCDN version'));?>:</span>
                        <span class="version"><?php echo $block->escapeHtml($this->getVersionNumber()); ?></span>
                    </li>
                    <span class="text"><?php echo $block->escapeHtml(__('Your PHP version'));?>:</span>
                    <span class="version">
                            <a href="http://devdocs.magento.com/guides/v<?php echo $this->getMagentoVersionTidyString() ;?>/install-gde/system-requirements-tech.html"
                               target="_blank">
                                <?php echo $block->escapeHtml(implode('.', $this->getPhpVersionArray())); ?>
                                </a>
                                &nbsp;
                        <?php switch ($this->phpVersionCheck()) {
                            case 1:
                                echo '<img class="compatible-image" height="16" src="' . $this->getViewFileUrl(
                                        'TIG_TinyCDN::images/green-ok.png'
                                    ) . '" alt="">';
                                break;
                            case 0:
                                echo '<img class="compatible-image" height="16" src="' . $this->getViewFileUrl(
                                        'TIG_TinyCDN::images/red-nok.png'
                                    ) . '" alt="">';
                                break;
                            default:
                                echo '<img class="compatible-image" height="16" src="' . $this->getViewFileUrl(
                                        'TIG_TinyCDN::images/orange-unknown.png'
                                    ) . '" alt="">';
                                break;
                        }
                        ?>
                        </span>
                </ul>
            </div>
        </div>

        <div class="col-2 legend-version">
            <img class="panda-george" src="<?php echo $this->getViewFileUrl('TIG_TinyCDN::images/george-magento@2x_opt.png'); ?>" alt="George the TinyCDN panda" />
        </div>

    </div>

    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Support'));?></h3>
        </div>
        <div class="collapse-content support-tinycdn-tig" data-role="content" style="display:none;">
            <?php echo __('This extension is developed by <a href="https://tig.nl" target="_BLANK">TIG</a>');?>

            <div class="colset-2">
                <div class="col-1">
                    <h4><?php echo __('Extension basic configuration and account information');?></h4>
                    <?php echo __('Please contact:'); ?> <a href="mailto:support@tinypng.com">support@tinypng.com</a>
                </div>
                <div class="col-2">

                </div>

            </div>
        </div>
    </div>
</div>
