<?php
/** @var \TIG\TinifyCDN\Block\Adminhtml\Config\Support\Tab $this */
?>
<div id="supporttab" class="tig-tinifycdn-supporttab" data-mage-init='{"tinifyConfig": true}'>
    <div class="colset-2">
        <div class="col-1 legend-version">
            <div class="version-compatibility">
                <h3><?php echo $block->escapeHtml(__('Magento version compatibility')); ?></h3>
                <ul>
                    <li>
                    <span class="text">
                        <?php echo $block->escapeHtml(__('Supported Magento versions')); ?>:
                    </span>
                        <span class="version"><?php echo $block->escapeHtml($this->getSupportedMagentoVersions()); ?></span>
                    </li>
                    <li>
                        <span class="text"><?php echo $block->escapeHtml(__('Tinify CDN version')); ?>:</span>
                        <span class="version"><?php echo $block->escapeHtml($this->getVersionNumber()); ?></span>
                    </li>
                    <span class="text"><?php echo $block->escapeHtml(__('Your PHP version')); ?>:</span>
                    <span class="version">
                        <a href="http://devdocs.magento.com/guides/v<?php echo $this->getMagentoVersionTidyString(); ?>/install-gde/system-requirements-tech.html" target="_blank">
                            <?php echo $block->escapeHtml(implode('.', $this->getPhpVersionArray())); ?>
                        </a>
                                &nbsp;
                        <?php
                        switch ($this->phpVersionCheck()) {
                            case 1:
                                ?>
                                <img class="compatible-image" height="16" src="<?= $this->getViewFileUrl('TIG_TinifyCDN::images/green-ok.png'); ?>" alt="">
                                <?php
                                break;
                            case 0:
                                ?>
                                <img class="compatible-image" height="16" src="<?= $this->getViewFileUrl('TIG_TinifyCDN::images/red-nok.png'); ?>" alt="">
                                <?php
                                break;
                            default:
                                ?>
                                <img class="compatible-image" height="16" src="<?= $this->getViewFileUrl('TIG_TinifyCDN::images/orange-unknown.png'); ?>" alt="">
                                <?php
                                break;
                        }
                        ?>
                    </span>
                </ul>
            </div>
        </div>
        <div class="col-2 legend-version">
            <img class="panda-george" src="<?php echo $this->getViewFileUrl('TIG_TinifyCDN::images/george-magento@2x_opt.png'); ?>" alt="George the Tinify CDN panda"/>
        </div>
    </div>

    <div id="section">
        <div class="collapse-title" data-role="title">
            <h3 data-role="trigger"><?php echo $block->escapeHtml(__('Support')); ?></h3>
        </div>
        <div class="collapse-content support-tinifycdn-tig" data-role="content" style="display:none;">
            <?php echo __('This extension is developed by <a href="https://tig.nl" target="_BLANK">TIG</a>'); ?>
            <div class="colset-2">
                <div class="col-1">
                    <h4><?php echo __('Extension basic configuration and account information'); ?></h4>
                    <?php echo __('Please contact:'); ?>
                    <a href="mailto:support@tinify.com">support@tinify.com</a>
                </div>
            </div>
        </div>
    </div>
</div>
