<?php
/**
 *
 *          ..::..
 *     ..::::::::::::..
 *   ::'''''':''::'''''::
 *   ::..  ..:  :  ....::
 *   ::::  :::  :  :   ::
 *   ::::  :::  :  ''' ::
 *   ::::..:::..::.....::
 *     ''::::::::::::''
 *          ''::''
 *
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL:
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@tig.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@tig.nl for more information.
 *
 * @copyright   Copyright (c) Total Internet Group B.V. https://tig.nl/copyright
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */

namespace TIG\TinifyCDN\Controller\Cdn;

use Magento\Backend\Model\UrlInterface;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\Action\Context;
use TIG\TinifyCDN\Exception;
use TIG\TinifyCDN\Model\Config\Source\Cdn\Url;

class Redirect extends Action
{
    /** @var Exception $exception */
    private $exception;

    /** @var Url $urlBuilder */
    private $urlBuilder;

    /**
     * Redirect constructor.
     *
     * @param Context   $context
     * @param Exception $exception
     * @param Url       $urlBuilder
     */
    public function __construct(
        Context $context,
        Exception $exception,
        Url $urlBuilder
    ) {
        $this->exception  = $exception;
        $this->urlBuilder = $urlBuilder;
        parent::__construct($context);
    }

    /**
     * This frontend controller is used to receive all parameters from Tinify and authenticate them.
     * If the state-parameter does not match the form-key generated by Magento earlier, the user is
     * redirected to the login-page (if no admin-session is active) or the dashboard (if an active
     * admin-session is available).
     *
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\Result\Redirect|\Magento\Framework\Controller\ResultInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function execute()
    {
        $params = $this->getRequest()->getParams();

        if (!isset($params['code']) && !isset($params['state'])) {
            return $this->exception->throwException('Invalid request. No direct access allowed.');
        }
        $redirect = $this->resultRedirectFactory->create();

        // Error handled by authorization controller
        if (isset($params['error'])) {
            $authUrl = $this->urlBuilder->createAuthorizeUrl(
                [
                    UrlInterface::SECRET_KEY_PARAM_NAME => $params['state'],
                    'error' => $params['error']
                ]
            );
            $redirect->setPath($authUrl);
            return $redirect;
        }

        $authUrl = $this->urlBuilder->createAuthorizeUrl(
            [
                UrlInterface::SECRET_KEY_PARAM_NAME => $params['state'],
                'code'                              => $params['code']
            ]
        );

        $redirect->setPath($authUrl);

        return $redirect;
    }
}
